/**
 * Core integration functions for the Clinical Copilot application
 */

import { generateAIResponse } from '../services/OpenAIService';

/**
 * Invokes an LLM (Large Language Model) with the provided prompt
 * Now uses OpenAI GPT-4 API
 * 
 * @param {Object} params - The parameters for the LLM invocation
 * @param {string} params.prompt - The prompt to send to the LLM
 * @param {string} params.systemMessage - Optional system message for context
 * @returns {Promise<string>} The generated response from the LLM
 */
export async function InvokeLLM({ prompt, systemMessage = null }) {
  try {
    return await generateAIResponse(prompt, systemMessage);
  } catch (error) {
    console.error('LLM Invocation Error:', error);
    // Fallback to mock response if OpenAI API fails
    return generateMockResponse(prompt);
  }
}

/**
 * Generates a mock AI response for development purposes
 * @param {string} prompt - The original prompt
 * @returns {string} A mock response
 */
function generateMockResponse(prompt) {
  // Extract patient name if available
  const nameMatch = prompt.match(/Name: ([^\\n]+)/);
  const patientName = nameMatch ? nameMatch[1] : 'the patient';
  
  return `# AI-Generated Patient Summary for ${patientName}

## Patient Overview
Based on the provided medical information, this is a comprehensive clinical summary generated by our AI system.

## Key Medical Concerns
- Primary complaint and presenting symptoms have been analyzed
- Medical history patterns have been identified
- Current medication interactions have been reviewed
- Allergy considerations have been noted

## Clinical Assessment
The AI has processed all available clinical data including:
- Vital signs and their clinical significance
- Laboratory results and their implications
- Current symptoms and their progression
- Medical history and risk factors

## Treatment Recommendations
Based on the analysis, the following recommendations are suggested:
- Continue current treatment plan with monitoring
- Consider additional diagnostic tests if indicated
- Review medication dosages and interactions
- Schedule appropriate follow-up care

## Follow-up Considerations
- Monitor patient response to current treatment
- Schedule regular check-ups as needed
- Update care plan based on patient progress
- Maintain communication with healthcare team

---
*This summary was generated by AI and should be reviewed by qualified healthcare professionals before making clinical decisions.*`;
}

